// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package cn.teamthevoid.AiTankArenaServer.message.operation;

/**
 * Protobuf enum {@code AiTankArenaServer.WeaponState}
 */
public enum WeaponState
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 武器空闲中
     * </pre>
     *
     * <code>IDLE = 0;</code>
     */
    IDLE(0),
    /**
     * <pre>
     * 武器已被触发 例如 开炮中
     * </pre>
     *
     * <code>ACTIVE = 1;</code>
     */
    ACTIVE(1),
    /**
     * <pre>
     * 武器冷却中
     * </pre>
     *
     * <code>COOL_DOWN = 2;</code>
     */
    COOL_DOWN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 武器空闲中
     * </pre>
     *
     * <code>IDLE = 0;</code>
     */
    public static final int IDLE_VALUE = 0;
    /**
     * <pre>
     * 武器已被触发 例如 开炮中
     * </pre>
     *
     * <code>ACTIVE = 1;</code>
     */
    public static final int ACTIVE_VALUE = 1;
    /**
     * <pre>
     * 武器冷却中
     * </pre>
     *
     * <code>COOL_DOWN = 2;</code>
     */
    public static final int COOL_DOWN_VALUE = 2;
    private static final com.google.protobuf.Internal.EnumLiteMap<
            WeaponState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WeaponState>() {
                public WeaponState findValueByNumber(int number) {
                    return WeaponState.forNumber(number);
                }
            };
    private static final WeaponState[] VALUES = values();
    private final int value;

    private WeaponState(int value) {
        this.value = value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WeaponState valueOf(int value) {
        return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static WeaponState forNumber(int value) {
        switch (value) {
            case 0:
                return IDLE;
            case 1:
                return ACTIVE;
            case 2:
                return COOL_DOWN;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WeaponState>
    internalGetValueMap() {
        return internalValueMap;
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
        return cn.teamthevoid.AiTankArenaServer.message.operation.Game.getDescriptor().getEnumTypes().get(2);
    }

    public static WeaponState valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    // @@protoc_insertion_point(enum_scope:AiTankArenaServer.WeaponState)
}

