// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package cn.teamthevoid.AiTankArenaServer.message;

public interface OperationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:AiTankArenaServer.Operation)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.AiTankArenaServer.OperationType type = 1;</code>
   *
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();

  /**
   * <code>.AiTankArenaServer.OperationType type = 1;</code>
   *
   * @return The type.
   */
  cn.teamthevoid.AiTankArenaServer.message.OperationType getType();

  /**
   * <code>string message = 2;</code>
   *
   * @return The message.
   */
  java.lang.String getMessage();

  /**
   * <code>string message = 2;</code>
   *
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
  getMessageBytes();
}
