// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package cn.teamthevoid.AiTankArenaServer.message;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AiTankArenaServer.People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();
}
