// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package cn.teamthevoid.AiTankArenaServer.message;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AiTankArenaServer_People_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AiTankArenaServer_People_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\021AiTankArenaServer\"\"\n\006Peopl" +
      "e\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005B,\n(cn.teamth" +
      "evoid.AiTankArenaServer.messageP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AiTankArenaServer_People_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AiTankArenaServer_People_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AiTankArenaServer_People_descriptor,
        new java.lang.String[] { "Name", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
