# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='share.proto',
  package='AiTankArenaServer',
  syntax='proto3',
  serialized_options=b'\n2cn.teamthevoid.AiTankArenaServer.message.operationP\001',
  serialized_pb=b'\n\x0bshare.proto\x12\x11\x41iTankArenaServer\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Rect\x12\x12\n\nposTopLeft\x18\x01 \x01(\x02\x12\x16\n\x0eposBottomRight\x18\x02 \x01(\x02\x42\x36\n2cn.teamthevoid.AiTankArenaServer.message.operationP\x01\x62\x06proto3'
)

_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='AiTankArenaServer.Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AiTankArenaServer.Vector2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AiTankArenaServer.Vector2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=66,
)

_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='AiTankArenaServer.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='AiTankArenaServer.Vector3D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='AiTankArenaServer.Vector3D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='AiTankArenaServer.Vector3D.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=111,
)

_RECT = _descriptor.Descriptor(
  name='Rect',
  full_name='AiTankArenaServer.Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='posTopLeft', full_name='AiTankArenaServer.Rect.posTopLeft', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='posBottomRight', full_name='AiTankArenaServer.Rect.posBottomRight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), {
  'DESCRIPTOR': _VECTOR2D,
  '__module__': 'share_pb2'
  # @@protoc_insertion_point(class_scope:AiTankArenaServer.Vector2D)
})
_sym_db.RegisterMessage(Vector2D)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), {
  'DESCRIPTOR': _VECTOR3D,
  '__module__': 'share_pb2'
  # @@protoc_insertion_point(class_scope:AiTankArenaServer.Vector3D)
})
_sym_db.RegisterMessage(Vector3D)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), {
  'DESCRIPTOR': _RECT,
  '__module__': 'share_pb2'
  # @@protoc_insertion_point(class_scope:AiTankArenaServer.Rect)
})
_sym_db.RegisterMessage(Rect)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
